name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}  # Continue after failures
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", 3.9]
        experimental: [false]  # These versions must pass.

    env:
      GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Set token for Coveralls.

    steps:
    - uses: actions/checkout@v2  # Checkout repo.

    - name: Set up production Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display python version.
      run: python --version --version && which python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_dev.txt

    - name: Test with pytest --cov=./ --mypy -vv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pytest --cov=./ --mypy -vv
        coverage xml -i
        coveralls --service=github

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      if: matrix.os == 'ubuntu_latest'
      with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

    - name: Codecov  # upload
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        name: codecov-umbrella # Optional.
        fail_ci_if_error: false # Allow codecov to signal fail rather than action failing.
        verbose: true # Optional (default = false).

  coveralls_finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished report
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ github.token }}
          parallel: true
          parallel-finished: true
          flag-name: github_action_tests
          base-path: '.'
          debug: true
